### PR TITLE
fixing the xref/href inconsistency

### PR DESCRIPTION
**Pull request by kohlhase**
this is really what I mean

### CODE REVIEW

**Comment by JamesHDavenport** [comment]
MY personal view is that this belongs in 2.0r2 - @davidcarlisle : can we start one (probably needed  anyway);  @pdfion - do you agree?

**Comment by davidcarlisle** [comment]
a second revision is effectively started anyway

travis (unless you put "final" in the checkin message) always builds into
"editors-draft" so you can move ahead of the current release and just call
it release n+1, and copy it to a "dated" directory when there have been
enough edits to call it a new revison.

so we can fix this in the master branch in OMSTD now (by accepting the PR
from Michael)

**Comment by davidcarlisle** [comment]
Taking James' comment above as agreeing this change needs doing I'll merge this and start a new issue about 2.0r2

**Comment by pdfion** [comment]
Yes, clearly a new draft needs starting, or as David remarks
is implicitly already.

Patrick

**Pull request merged**
