### PR TITLE
update to IRI spec, issue #29

### PR DESCRIPTION
**Pull request by davidcarlisle**

### CODE REVIEW

**Comment by davidcarlisle** [comment]
OK I made a PR @kohlhase yu might want to check my IRI statements @pdfion @JamesHDavenport  you probably don't want to trust my typing:-)  (Patrick I pinged you in particular as you don't seem to be watching this repo so miss issue notifications)

**Comment by kohlhase** [comment]
Is there really no xsd data type like `xsd:anyIRI`? It seems a bit of a pity to have to revert to `xsd:string`. I could not find one, have people lost interest in this?

**Comment by kohlhase** [comment]
Otherwise things seem fine. From my point of view this can be merged.

**Comment by davidcarlisle** [comment]
anyURL was clarified to mean essentially any URI but since it only talks of validation not actually the mapping to the %-encoded URL it means that any string is valid and characters not allowed in URL are assumed to be %-encoded by the application. so XSD made it explicit that the value spaces of anuURI and string are the same.  So it would be nice to leave it as anyURI (and I wouldn't necessarily object to reverting that part of the suggested change) but then older relax (and XSD) validators may or may not validate CDURL elements containing non URL characters depending if they folow teh XSD 1.1 interpretation (when any content is valid) or try to follow the XSD 1.0 interpretation (which was incoherent and sometimes implied things had to be URL %-encoded, and sometimes implied they did not)

In practice if we use anyURI and avoid (as has already been done) white space things will be valid and look more natural, perhaps over time validators will catch up (or people will ignore formal validation)

**Comment by kohlhase** [comment]
> In practice if we use anyURI and avoid (as has already been done) white space things will be valid and look more natural, perhaps over time validators will catch up (or people will ignore formal validation)

Actually I am fine either way. I will trust your instincts on this.

**Comment by davidcarlisle** [comment]
I think I'll revert it to anyURI and adjust the  bit in the text where I justified to use xsd:string, I'll do that before pulling the pr, although perhaps not today

**Comment by pdfion** [comment]
I wasn't Git-watching, which I'll change if necessary, but I'm getting
lots of Travis notifications, which I thought enough.

Patrick

**Pull request merged**
