### PR TITLE
Clarifying and partially fixing alpha-conversion and bound variables in OM2

### PR DESCRIPTION
**Pull request by kohlhase**
This pull request contains the fixes for #30 and #40. As this is a complex topic, this will require multiple commits.

It is still under development, so do not merge it yet, but possibly give early feedback as the commits flow in.

### CODE REVIEW

**Comment by kohlhase** [comment]
I have updated this PR to the trunk and think it is ready to go. 
@davidcarlisle could you please have a look and merge if you like it?

**Comment by kohlhase** [comment]
BTW, the change is so large, since I had to (manually) format the MathML to make sense of it while editing.

**Comment by florian-rabe** [comment]
I'm commenting on #53:

Using my definitions in #64, #53 can be resolved easily.
However, as described in #64, we have to choose between two options.
Depending on the choice, the resolution to #53 varies:

* sequential binding: Duplicate variables are not a problem anymore because their semantics is clearly specified. They are pointless but should be allowed.
The remark "Repeated occurrences of the same variable in a binding operator ..." in the standard should be revised to clarify that it is just an example of a consequence of the definition of binding and alpha-conversion.
* parallel binding: Duplicate variables should be forbidden.

**Comment by florian-rabe** [comment]
Michael asked about variants of parallel binding that do not forbid duplicate variables.
Here's one option:

In a binding object, essentially all variable bindings govern each other.
The precise definition is more technical because it has to cover the case where the same variable name is bound multiple times in the same binding object: In a binding object with variable bindings b_1, ..., b_n, the variable reference b_i governs the list of variable bindings that results from cutting off b_{i+1}, ..., b_n, b_1, ..., b_i after the first binding with the same name as b_i.

This somewhat convoluted definition has the effect that the following examples work:

* singly or mutually recursive bindings without duplicates variable names, e.g., let x=f(y), y=g(x) in O
* sequential bindings with shadowing semantics for duplicate variable names, e.g., let x = 1, x=x+1 in x (which evaluates to 2)

**Pull request merged**
